"""add person and face_embedding tables

Revision ID: 824c17b867db
Revises: e125aa01171c
Create Date: 2026-05-26 02:34:48.924840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824c17b867db'
down_revision = 'e125aa01171c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('face_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding_id', sa.String(length=255), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('person_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('embedding_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_embedding')
    op.drop_table('person')
    # ### end Alembic commands ###
